version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:bionic
    environment:
      PYTHON_VERSION: 3.8.10
    steps:
      - checkout
      - run:
          name: Setup Miniconda
          command: |
            apt update
            apt install -y wget
            cd $HOME
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -b -p $HOME/miniconda
      - run:
          name: Setup environment and run tests
          command: |
            export PATH="$HOME/miniconda/bin:$PATH"
            conda update -y conda
            conda create -n test-env python=3.8 setuptools pytest pyqt=5.* qt=5.*
            activate test-env
            python -m pip install pytest-qt
      - run:
          name: Running tests
          command: |
            activate test-env
            python -m pytest guitest.py
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
